# backend/services/ai_detector.py
import re
from typing import Tuple, Dict
import logging

logger = logging.getLogger(__name__)

class AICodeDetector:
    """
    Advanced AI-generated code detection system.
    Analyzes multiple signals to detect if code was likely generated by AI.
    """
    
    # AI models often use these specific patterns
    AI_COMMENT_PATTERNS = [
        r'# Helper function',
        r'# Main function',
        r'# Initialize',
        r'# Create',
        r'# Check if',
        r'# Return',
        r'# Edge case',
        r'# Base case',
        r'# Iterate through',
        r'# Calculate',
    ]
    
    # AI models love these variable names
    AI_VARIABLE_PATTERNS = [
        r'\bresult\b',
        r'\btemp\b',
        r'\bhelper\b',
        r'\baux\b',
        r'\bn\b(?=\s*=)',
        r'\bi\b(?=\s+in\s+range)',
        r'\bcurrent\b',
        r'\bprev\b',
    ]
    
    # AI often uses overly descriptive function names
    AI_FUNCTION_NAMES = [
        'helper',
        'solve',
        'calculate',
        'process',
        'find',
        'get_result',
        'compute',
    ]
    
    def __init__(self, threshold: int = 40):
        """
        Initialize detector with suspicion threshold.
        
        Args:
            threshold: Score above which code is flagged as AI (0-100)
        """
        self.threshold = threshold
    
    def is_ai_generated(self, code: str) -> Tuple[bool, int, Dict[str, any]]:
        """
        Detect if code is AI-generated.
        
        Args:
            code: Source code to analyze
            
        Returns:
            Tuple of (is_ai, suspicion_score, breakdown)
        """
        if not code or len(code.strip()) < 20:
            return False, 0, {"reason": "Code too short to analyze"}
        
        breakdown = {}
        suspicion_score = 0
        
        # 1. Check for AI comment patterns (max 20 points)
        ai_comments = self._detect_ai_comments(code)
        comment_score = min(ai_comments * 5, 20)
        suspicion_score += comment_score
        breakdown['ai_comments'] = {
            'count': ai_comments,
            'score': comment_score,
            'weight': '20%'
        }
        
        # 2. Check for generic variable names (max 15 points)
        generic_vars = self._detect_generic_variables(code)
        var_score = min(generic_vars * 3, 15)
        suspicion_score += var_score
        breakdown['generic_variables'] = {
            'count': generic_vars,
            'score': var_score,
            'weight': '15%'
        }
        
        # 3. Check code structure perfection (max 25 points)
        structure_score = self._analyze_code_structure(code)
        suspicion_score += structure_score
        breakdown['perfect_structure'] = {
            'score': structure_score,
            'weight': '25%',
            'details': 'Perfect indentation, spacing, and formatting'
        }
        
        # 4. Check for overly verbose/explanatory style (max 20 points)
        verbosity_score = self._check_verbosity(code)
        suspicion_score += verbosity_score
        breakdown['verbosity'] = {
            'score': verbosity_score,
            'weight': '20%'
        }
        
        # 5. Check for AI function naming patterns (max 10 points)
        function_score = self._check_function_names(code)
        suspicion_score += function_score
        breakdown['ai_function_names'] = {
            'score': function_score,
            'weight': '10%'
        }
        
        # 6. Check for perfect error handling (max 10 points)
        error_handling_score = self._check_error_handling(code)
        suspicion_score += error_handling_score
        breakdown['error_handling'] = {
            'score': error_handling_score,
            'weight': '10%'
        }
        
        # Cap at 100
        suspicion_score = min(suspicion_score, 100)
        breakdown['total_score'] = suspicion_score
        breakdown['threshold'] = self.threshold
        breakdown['verdict'] = 'AI_GENERATED' if suspicion_score >= self.threshold else 'HUMAN_WRITTEN'
        
        is_ai = suspicion_score >= self.threshold
        
        logger.info(f"AI Detection - Score: {suspicion_score}/100, Is AI: {is_ai}")
        
        return is_ai, suspicion_score, breakdown
    
    def _detect_ai_comments(self, code: str) -> int:
        """Count AI-style comments"""
        count = 0
        for pattern in self.AI_COMMENT_PATTERNS:
            count += len(re.findall(pattern, code, re.IGNORECASE))
        return count
    
    def _detect_generic_variables(self, code: str) -> int:
        """Count generic variable names common in AI code"""
        count = 0
        for pattern in self.AI_VARIABLE_PATTERNS:
            matches = re.findall(pattern, code)
            count += len(matches)
        return count
    
    def _analyze_code_structure(self, code: str) -> int:
        """
        Analyze if code is TOO perfect (AI signature).
        Humans make small formatting mistakes, AI doesn't.
        """
        score = 0
        lines = code.split('\n')
        
        # Check if ALL lines are perfectly indented (4 spaces or tabs)
        perfect_indent = sum(1 for line in lines if line.startswith('    ') or line.startswith('\t') or not line.strip())
        if len(lines) > 0:
            indent_ratio = perfect_indent / len(lines)
            if indent_ratio > 0.8:  # 80% perfect indentation
                score += 10
        
        # Check for consistent spacing around operators
        operators = re.findall(r'[\+\-\*/=<>]', code)
        if operators:
            # AI always adds spaces: "x = y", humans often write "x=y"
            spaced_operators = len(re.findall(r'\s[\+\-\*/=<>]\s', code))
            if len(operators) > 0 and spaced_operators / len(operators) > 0.9:
                score += 10
        
        # Check for perfect blank line usage (AI loves blank lines)
        blank_lines = code.count('\n\n')
        if blank_lines > len(lines) * 0.15:  # More than 15% blank lines
            score += 5
        
        return score
    
    def _check_verbosity(self, code: str) -> int:
        """
        AI code tends to be overly verbose with explanatory variable names
        and unnecessary intermediate steps.
        """
        score = 0
        
        # Count long variable names (AI loves descriptive names)
        long_vars = re.findall(r'\b[a-z_]{10,}\b', code)
        if len(long_vars) > 3:
            score += 10
        
        # Count comment density (AI over-comments)
        comment_lines = len(re.findall(r'#.*', code))
        code_lines = len([l for l in code.split('\n') if l.strip()])
        if code_lines > 0:
            comment_ratio = comment_lines / code_lines
            if comment_ratio > 0.3:  # More than 30% comments
                score += 10
        
        return score
    
    def _check_function_names(self, code: str) -> int:
        """Check for AI-typical function names"""
        score = 0
        function_defs = re.findall(r'def\s+(\w+)\s*\(', code)
        
        for func_name in function_defs:
            if func_name.lower() in self.AI_FUNCTION_NAMES:
                score += 5
        
        return min(score, 10)
    
    def _check_error_handling(self, code: str) -> int:
        """
        AI often adds unnecessary try-except blocks even for simple code.
        Humans usually skip error handling in competitive programming.
        """
        score = 0
        
        # Count try-except blocks
        try_blocks = len(re.findall(r'\btry\s*:', code))
        
        # In competitive programming, error handling is usually unnecessary
        # If code has try-except, it might be AI-generated
        if try_blocks > 0:
            score += try_blocks * 5
        
        return min(score, 10)


# Global detector instance
ai_detector = AICodeDetector(threshold=65)