apiVersion: apps/v1
kind: Deployment
metadata:
  name: codearena-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codearena-backend
  template:
    metadata:
      labels:
        app: codearena-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ORG/REPO/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: production
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: MYSQL_PASSWORD
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: JWT_SECRET
            - name: EXECUTOR_URL
              value: http://codearena-executor:9090
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: FIREBASE_CLIENT_EMAIL
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: FIREBASE_PRIVATE_KEY
            - name: FIREBASE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: codearena-secrets
                  key: FIREBASE_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: codearena-backend
spec:
  selector:
    app: codearena-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080