name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Backend lint
        run: |
          pip install ruff
          ruff check backend

      - name: Backend unit tests
        run: |
          echo "No tests yet" # Placeholder for pytest

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend deps
        run: |
          cd frontend
          npm ci
          npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and push Executor
        uses: docker/build-push-action@v6
        with:
          context: .
          file: executor/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/executor:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest